document.writeln("        <div class=\"site-footer\">");
document.writeln("            <div class=\"container\">");
document.writeln("                <div class=\"row\">");
document.writeln("                    <div class=\"col-md-4 col-sm-4\">");
document.writeln("                        <div class=\"footer-logo\">");
document.writeln("                            <a href=\"index.html\">");
document.writeln("                                <img src=\"\" alt=\"\">");
document.writeln("                            </a>");
document.writeln("                        </div>");
document.writeln("                    </div> <!-- /.col-md-4 -->");
document.writeln("                    <div class=\"col-md-4 col-sm-4\">");
document.writeln("                        <div class=\"copyright\">");
document.writeln("                            <span>Copyright &copy; 2014 <a href=\"index.html#\">公司名称</a></span>");
document.writeln("                        </div>");
document.writeln("                    </div> <!-- /.col-md-4 -->");
document.writeln("                    <div class=\"col-md-4 col-sm-4\">");
document.writeln("                        <ul class=\"social-icons\">");
document.writeln("                            <li><a href=\"index.html#\" class=\"fa fa-weibo\"></a></li>");
document.writeln("                            <li><a href=\"index.html#\" class=\"fa fa-weixin\"></a></li>");
document.writeln("                            <li><a href=\"index.html#\" class=\"fa fa-qq\"></a></li>");
document.writeln("                            <li><a href=\"index.html#\" class=\"fa fa-rss\"></a></li>");
document.writeln("                        </ul>");
document.writeln("                    </div> <!-- /.col-md-4 -->");
document.writeln("                </div> <!-- /.row -->");
document.writeln("            </div> <!-- /.container -->");
document.writeln("        </div> <!-- /.site-footer -->");
document.writeln("");
document.writeln("        <script src=\"js/vendor/jquery-1.11.0.min.js\"></script>");
document.writeln("        <script>window.jQuery || document.write(\'<script src=\"js/vendor/jquery-1.11.0.min.js\"><\/\//script>\')</script>");
document.writeln("        <script src=\"js/bootstrap.js\"></script>");
document.writeln("        <script src=\"js/plugins.js\"></script>");
document.writeln("        <script src=\"js/main.js\"></script>");