_.namespace("Backbone.widgets",function(){return{ModalWindow:Backbone.Widget.extend({className:"backbone_modal_window",templates:{base:'<div class="window_wrap <%= d.window_wrap_class %>"><div class="close"><img src="//cdn.mxpnl.com/cache/14198de9715c736d73b43876b47f9f08/images/backbone_widgets/icon_x.png" /></div><div class="window"><div class="content"></div></div></div>'},events:{"click .close":"handle_close",click:"clickout"},initialize:function(){this.render_base_template(_.defaults(this.options,
{window_wrap_class:""}));this.hide();this.$el.appendTo(this.options.wrapper||"body");this.content=this.$(".content");_.isNumber(this.options.padding)?this.$(".window").css("padding",this.options.padding):this.options.padding=14;this.options.wrapper&&this.$el.css("position","absolute");var a,b;if(this.options.width)a="width",b=this.options.width;else if(this.options.min_width)a="min-width",b=this.options.min_width;else if(this.options.max_width)a="max-width",b=this.options.max_width;a&&this.$(".window_wrap").css(a,
b+2*this.options.padding);this.options.widget&&this.set_widget(this.options.widget);if(this.options.disable_close||this.options.hide_close)this.$el.addClass("close_disabled"),this.$(".close").hide();this.on_close(function(){this.widget&&this.widget.close();$(this.options.wrapper||window).off("resize.backbone_modal_widget")})},set_widget:function(a){this.widget&&this.widget.close();this.widget=a;this.content.empty().append(this.widget.el)},set_content:function(a){this.content.empty().append(a)},show:function(){this.$el.show();
this.content.children().show();$(this.options.wrapper||window).on("resize.backbone_model_widget",_.bind(this.resize,this)).resize();this.trigger("show")},hide:function(){this.$el.hide();$(this.options.wrapper||window).off("resize.backbone_modal_widget");this.trigger("hide")},is_visible:function(){return this.$el.is(":visible")},handle_close:function(){if(!this.options.disable_close&&(this.hide(),this.options.on_close))this.options.on_close()},clickout:function(a){a.target===this.el&&!this.options.prevent_clickout&&
this.handle_close()},resize:function(){var a=$(this.options.wrapper||window).width(),b=$(this.options.wrapper||window).height(),c=this.$(".window_wrap"),d=c.outerWidth(),f=c.outerHeight();c.css({top:this.options.top||b/2-f/2,left:a/2-d/2})}})}});_.namespace("Backbone.widgets",function(){var a=0,b=function(){};window.onYouTubeIframeAPIReady=function(){b()};return{YouTubeView:Backbone.Widget.extend({api_url:"//www.youtube.com/iframe_api",className:"backbone_youtube_view",templates:{base:"<div class='cover'><div class='play'></div><img></div><div id='<%= d.yt_id %>'></div>"},events:{"click .cover":"play"},initialize:function(){this.yt_id=_.sprintf("youtube_embed_%d",a++);this.player_ready=!1;this.$el.addClass(this.className);this.render();this.load(this.options.video_id,
this.options.cover_img_url,this.options.autoplay)},render:function(){this.render_base_template({yt_id:this.yt_id});this.cover=this.$(".cover");this.cover_img=this.$(".cover img");this.$el.css({position:"relative"})},listen_for_events:function(){this.on("video:play",function(){this.api.playVideo()});this.on("video:pause",function(){this.api.pauseVideo()});this.on("video:stop",function(){this.api.stopVideo()})},load_api:function(a){if(!this.loading_api&&$("#"+this.yt_id).length)this.loading_api=!0,
$($("script")[0]).before($("<script>").attr("src",this.api_url)),b=_.bind(this.api_loaded,this,a)},api_loaded:function(a){var d=_.bind(function(){this.player_ready=!0;this.listen_for_events();this.video_id&&this.load(this.video_id,this.cover_img_url,a||this.autoplay)},this),b=_.bind(function(a){switch(a.data){case 0:this.trigger("state:ended");this.stop_progress_tracking();break;case 1:this.trigger("state:playing");this.start_progress_tracking();break;case 2:this.trigger("state:paused");this.stop_progress_tracking();
break;case 3:this.trigger("state:buffering")}},this);this.api=new YT.Player(this.yt_id,{width:"100%",height:"100%",playerVars:{showinfo:0,rel:0,autohide:1,modestbranding:1,controls:2},events:{onReady:d,onStateChange:b}})},check_api:function(){try{return this.api.getPlayerState(),!0}catch(a){return!1}},check_player:function(a){return!this.check_api()?(this.load_api(a),!1):this.player_ready},start_progress_tracking:function(){this.time_tracking_id=window.setInterval(_.bind(function(){try{this.trigger("progress",
this.api.getCurrentTime()/this.api.getDuration())}catch(a){this.stop_progress_tracking()}},this),1E3)},stop_progress_tracking:function(){if(this.time_tracking_id)window.clearInterval(this.time_tracking_id),this.time_tracking_id=null},load:function(a,d,b){this.video_id=a;this.cover_img_url=d||void 0;this.autoplay=b;this.cover_img_url?(this.cover.show(),this.cover_img.attr("src",this.cover_img_url)):this.cover.hide();this.mw&&this.mw.resize();this.check_player()&&(this.api.cueVideoById(this.video_id),
this.api.setPlaybackQuality("hd720"),this.autoplay&&this.play())},play:function(){this.check_player(!0)&&(window.setTimeout(_.bind(function(){this.$el.height(9*this.$el.width()/16)},this),200),this.cover.hide(),this.video_id?this.api.loadVideoById(this.video_id,0,"hd720"):this.api.playVideo())},restart:function(){this.check_player(!0)&&(this.api.seekTo(0),this.play())}})}});_.namespace("mp.report",function(a){var b=Backbone.TemplateView.extend({className:"tutorial learn_video",templates:{base:'<div class="block"><div class="video"></div><h3><%= d.name %></h3><p><%= d.description %></p></div>'},default_options:{in_modal:!1,tab:null,report_style:"d2",video_id:null,video_thumb_url:null,tutorial_name:null,tutorial_description:null,init_track_shown:!0},initialize:function(){this.options=_.extend({},this.default_options,a.TutorialVideoManager.options,this.options);this.$el.addClass(this.className);
this.options.in_modal?this.options.init_track_shown&&this.track_shown():this.$el.addClass(this.options.report_style);this.render_base_template({name:this.options.tutorial_name,description:this.options.tutorial_description});this.render_player()},track_shown:function(){mixpanel.track("Tutorial Shown",{tab:this.options.tab})},render_player:function(){this.player=new Backbone.widgets.YouTubeView({el:this.$(".video"),video_id:this.options.video_id,cover_img_url:this.options.video_thumb_url});var a=!1,
b={75:!1,50:!1,25:!1};this.player.on("state:playing",function(){a||(mixpanel.track("Tutorial Video Started",{tab:this.options.tab}),a=!0)},this);this.player.on("state:ended",function(){mixpanel.track("Tutorial Video Finished",{tab:this.options.tab})},this);this.player.on("progress",_.bind(function(a){var d=null;_.any(b,function(c,e){e=Number(e);if(!c&&100*a>e)return d=e,b[e]=!0});d&&mixpanel.track(_.sprintf("Tutorial Video Progress (%f%%)",d),{tab:this.options.tab})},this));this.on("all",function(a){this.player.trigger(a)})},
restart:function(){this.player.restart()}}),c=Backbone.View.extend({default_options:{check_flags:[],set_flag:null},setup:function(a){this.options=_.extend({},this.default_options,a);this.options.el&&(this.setElement(this.options.el),delete this.options.el)},show:function(){this.tutorial=new b({el:this.el})},create_modal:function(){if(!this.modal){var a=new b(_.extend(this.options,{in_modal:!0}));this.modal=new Backbone.widgets.ModalWindow({width:850,widget:a,on_close:_.bind(function(){this.modal.hide();
this.message&&this.message.close();mixpanel.track("Tutorial Modal Closed",{tab:this.options.tab});this.options.set_flag&&mp.utility.set_flag(this.options.set_flag);a.trigger("video:pause")},this)})}},maybe_show_message:function(){var a=mp.report.globals.is_engage_resource?mp.report.globals.has_integrated_engage:mp.report.globals.has_integrated_arb,b=_.any(this.options.check_flags,function(a){return _.has(mp.report.globals.flags,a)}),c=0===$("#messages .message").length;a&&c&&!b&&this.show_message()},
show_message:function(){this.create_modal();mixpanel.track("Tutorial Banner Shown",{tab:this.options.tab});if(!this.message)this.message=new Backbone.widgets.ReportMessage({closable:!0,type:"video",title:_.sprintf("Watch a tutorial to learn how to use %s",this.options.tutorial_name),content:"Mixpanel has a lot to offer and the fastest way our other customers have become data driven is by watching this tutorial. It's really short and can save you a lot of time.",button_text:"Watch Video",button_callback:_.bind(function(){mixpanel.track("Tutorial Modal Shown",
{tab:this.options.tab});this.modal.show();this.modal.$el.find(".cover").click()},this),close_callback:_.bind(function(){mixpanel.track("Tutorial Banner Closed",{tab:this.options.tab});mp.utility.set_flag(this.options.set_flag)},this)})},show_modal:function(){this.create_modal();this.modal.show();this.modal.widget.restart()}});c.setup=function(a){c.options=a};return{TutorialVideo:b,TutorialVideoManager:new c}});

//# sourceMappingURL=/site_media/bundle/landing_common.min.js.map
